services:
  
  h:
    build:
      context: ./h/private
    command: 'tail -F anything'
  e:
    build:
      context: ./e/private
    command: 'tail -F anything'
  i:
    build:
      context: ./i/private
    command: 'tail -F anything'
  f:
    build:
      context: ./f/private
    command: 'tail -F anything'
  d:
    build:
      context: ./d/private
    command: 'tail -F anything'
  c:
    build:
      context: ./c/private
    command: 'tail -F anything'
  g:
    build:
      context: ./g/private
    command: 'tail -F anything'
  b:
    build:
      context: ./b/private
    command: 'tail -F anything'
  a:
    build:
      context: ./a/private
    command: 'tail -F anything'